# Generated by Django 3.2 on 2024-06-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20240623_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['name'], 'verbose_name': 'произведение', 'verbose_name_plural': 'Произведения'},
        ),
    ]
