# Generated by Django 3.2 on 2024-06-18 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20240618_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titlegenre',
            options={'verbose_name': 'произведение/жанр', 'verbose_name_plural': 'Произведение/Жанр'},
        ),
        migrations.AlterField(
            model_name='titlegenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.genre', verbose_name='жанр'),
        ),
        migrations.AlterField(
            model_name='titlegenre',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.title', verbose_name='название'),
        ),
    ]
