# Generated by Django 3.2 on 2024-06-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_title_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['id'], 'verbose_name': 'произведение', 'verbose_name_plural': 'Произведения'},
        ),
    ]
